[2022-05-26 01:10:33,061] [plex_meta_manager.py:122]  [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,062] [plex_meta_manager.py:123]  [INFO]     |                                                                                                    |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:124]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:125]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:126]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:127]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:128]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:129]  [INFO]     |                                                                            |___/                   |
[2022-05-26 01:10:33,063] [plex_meta_manager.py:130]  [INFO]     |     Version: 1.16.5                                                                                |
[2022-05-26 01:10:33,399] [plex_meta_manager.py:149]  [DEBUG]    |====================================================================================================|
[2022-05-26 01:10:33,399] [plex_meta_manager.py:150]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-05-26 01:10:33,399] [plex_meta_manager.py:151]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-05-26 01:10:33,399] [plex_meta_manager.py:152]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:153]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:154]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:155]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:156]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:157]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:158]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:159]  [DEBUG]    | --run-metadata-files (PMM_METADATA_FILES): None                                                    |
[2022-05-26 01:10:33,400] [plex_meta_manager.py:160]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-ghost (PMM_IGNORE_GHOST): False                                                           |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-05-26 01:10:33,401] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:172]  [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,402] [plex_meta_manager.py:172]  [INFO]     |                                            Starting Run                                            |
[2022-05-26 01:10:33,402] [plex_meta_manager.py:172]  [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,402] [config.py:58]              [INFO]     | Locating config...                                                                                 |
[2022-05-26 01:10:33,402] [config.py:64]              [INFO]     | Using //config/config.yml as config                                                                |
[2022-05-26 01:10:33,449] [config.py:252]             [WARNING]  | Config Warning: Path does not exist: /config/assets                                                |
[2022-05-26 01:10:33,450] [config.py:282]             [WARNING]  | Config Warning: No Paths exist using ['//config/assets'] as default                                |
[2022-05-26 01:10:33,450] [config.py:338]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,450] [config.py:354]             [WARNING]  | notifiarr attribute not found                                                                      |
[2022-05-26 01:10:33,450] [config.py:373]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,450] [config.py:378]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-05-26 01:10:33,569] [config.py:386]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-05-26 01:10:33,569] [config.py:390]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,569] [config.py:404]             [WARNING]  | omdb attribute not found                                                                           |
[2022-05-26 01:10:33,569] [config.py:406]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,569] [config.py:421]             [WARNING]  | mdblist attribute not found                                                                        |
[2022-05-26 01:10:33,570] [config.py:423]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,570] [config.py:427]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-05-26 01:10:33,702] [config.py:438]             [INFO]     | Trakt Connection Successful                                                                        |
[2022-05-26 01:10:33,703] [config.py:442]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,703] [config.py:458]             [WARNING]  | mal attribute not found                                                                            |
[2022-05-26 01:10:33,703] [config.py:473]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,703] [config.py:496]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-05-26 01:10:33,882] [config.py:508]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,882] [config.py:510]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-05-26 01:10:33,882] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,882] [config.py:581]             [INFO]     |                                        Movies Configuration                                        |
[2022-05-26 01:10:33,882] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:33,883] [config.py:582]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:33,883] [config.py:583]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-05-26 01:10:33,883] [config.py:584]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:33,884] [config.py:750]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:33,884] [config.py:751]             [INFO]     |======================================== Plex Configuration ========================================|
[2022-05-26 01:10:33,884] [library.py:107]            [INFO]     |                                                                                                    |
[2022-05-26 01:10:33,884] [library.py:109]            [INFO]     | Using Asset Directory: //config/assets                                                             |
[2022-05-26 01:10:34,032] [config.py:761]             [INFO]     | Movies Library Connection Successful                                                               |
[2022-05-26 01:10:34,032] [config.py:769]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,032] [config.py:770]             [INFO]     |===================================== Scanning Metadata Files ======================================|
[2022-05-26 01:10:34,032] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,032] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/People.yml                                                    |
[2022-05-26 01:10:34,032] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,049] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully                                                                  |
[2022-05-26 01:10:34,050] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,050] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Franchises.yml                                                |
[2022-05-26 01:10:34,050] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,118] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully                                                                  |
[2022-05-26 01:10:34,118] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,118] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Studios.yml                                                   |
[2022-05-26 01:10:34,118] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,132] [meta.py:100]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 95, in load_file
                                                                 |     data, _, _ = yaml.util.load_yaml_guess_indent(content)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/util.py", line 186, in load_yaml_guess_indent
                                                                 |     return yaml.load(yaml_str, **kw), indent, block_seq_indent  # type: ignore
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
                                                                 |     return constructor.get_single_data()
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
                                                                 |     return self.construct_document(node)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 131, in construct_document
                                                                 |     for _dummy in generator:
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1569, in construct_yaml_map
                                                                 |     self.construct_mapping(node, data, deep=True)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1452, in construct_mapping
                                                                 |     value = self.construct_object(value_node, deep=deep)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
                                                                 |     data = self.construct_non_recursive_object(node)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 196, in construct_non_recursive_object
                                                                 |     for _dummy in generator:
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1569, in construct_yaml_map
                                                                 |     self.construct_mapping(node, data, deep=True)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1453, in construct_mapping
                                                                 |     if self.check_mapping_key(node, key_node, maptyp, key, value):
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 294, in check_mapping_key
                                                                 |     raise DuplicateKeyError(*args)
                                                                 | ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
                                                                 |   in "<unicode string>", line 12, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 12)
                                                                 | found duplicate key "Disney Animated" with value "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/71183')])), ('sort_title', '+++++++DisneyLiveAction'), ('imdb_list', ['https://www.imdb.com/list/ls083312980/'])])" (original value: "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/11845')])), ('sort_title', '+++++++DisneyAnimated'), ('trakt_list', ['https://trakt.tv/users/kieranr27/lists/studio-disney-animation-copy?sort=released,desc'])])")
                                                                 |   in "<unicode string>", line 17, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 17)
                                                                 | 
                                                                 | To suppress this check see:
                                                                 |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
                                                                 | 
                                                                 | 
[2022-05-26 01:10:34,136] [library.py:125]            [ERROR]    | YAML Error: while constructing a mapping
                                                                 |   in "<unicode string>", line 12, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 12)
                                                                 | found duplicate key "Disney Animated" with value "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/71183')])), ('sort_title', '+++++++DisneyLiveAction'), ('imdb_list', ['https://www.imdb.com/list/ls083312980/'])])" (original value: "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/11845')])), ('sort_title', '+++++++DisneyAnimated'), ('trakt_list', ['https://trakt.tv/users/kieranr27/lists/studio-disney-animation-copy?sort=released,desc'])])")
                                                                 |   in "<unicode string>", line 17, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 17)
                                                                 | 
                                                                 | To suppress this check see:
                                                                 |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
                                                                 | 
[2022-05-26 01:10:34,137] [meta.py:267]               [INFO]     | 
[2022-05-26 01:10:34,137] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Holiday.yml
[2022-05-26 01:10:34,137] [meta.py:269]               [INFO]     | 
[2022-05-26 01:10:34,169] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully
[2022-05-26 01:10:34,170] [meta.py:267]               [INFO]     | 
[2022-05-26 01:10:34,170] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Charts.yml
[2022-05-26 01:10:34,170] [meta.py:269]               [INFO]     | 
[2022-05-26 01:10:34,181] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully
[2022-05-26 01:10:34,181] [config.py:853]             [INFO]     | 
[2022-05-26 01:10:34,181] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,181] [config.py:581]             [INFO]     |                                       TV Shows Configuration                                       |
[2022-05-26 01:10:34,181] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,181] [config.py:582]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,181] [config.py:583]             [INFO]     | Connecting to TV Shows Library...                                                                  |
[2022-05-26 01:10:34,181] [config.py:584]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,182] [config.py:750]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,182] [config.py:751]             [INFO]     |======================================== Plex Configuration ========================================|
[2022-05-26 01:10:34,182] [library.py:107]            [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,182] [library.py:109]            [INFO]     | Using Asset Directory: //config/assets                                                             |
[2022-05-26 01:10:34,298] [config.py:761]             [INFO]     | TV Shows Library Connection Successful                                                             |
[2022-05-26 01:10:34,298] [config.py:769]             [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,299] [config.py:770]             [INFO]     |===================================== Scanning Metadata Files ======================================|
[2022-05-26 01:10:34,299] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,299] [meta.py:268]               [INFO]     | Loading Metadata File: config/TVShows.yml                                                          |
[2022-05-26 01:10:34,299] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,299] [meta.py:100]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 94, in load_file
                                                                 |     raise Failed(f"File Error: File does not exist {os.path.abspath(file_path)}")
                                                                 | modules.util.Failed: File Error: File does not exist /config/TVShows.yml
                                                                 | 
[2022-05-26 01:10:34,300] [library.py:125]            [ERROR]    | YAML Error: File Error: File does not exist /config/TVShows.yml
[2022-05-26 01:10:34,300] [config.py:853]             [INFO]     | 
[2022-05-26 01:10:34,300] [config.py:856]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,300] [config.py:861]             [INFO]     | 2 Plex Library Connections Successful                                                              |
[2022-05-26 01:10:34,300] [config.py:865]             [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,300] [plex_meta_manager.py:211]  [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:212]  [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,301] [plex_meta_manager.py:212]  [INFO]     |                                           Movies Library                                           |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:212]  [INFO]     |====================================================================================================|
[2022-05-26 01:10:34,301] [plex_meta_manager.py:217]  [DEBUG]    |                                                                                                    |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:218]  [DEBUG]    | Mapping Name: Movies                                                                               |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:219]  [DEBUG]    | Folder Name: Movies                                                                                |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:220]  [DEBUG]    | Missing Path: //config/Movies_missing.yml                                                          |
[2022-05-26 01:10:34,301] [plex_meta_manager.py:222]  [DEBUG]    | Asset Directory: //config/assets                                                                   |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:223]  [DEBUG]    | Asset Folders: True                                                                                |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:224]  [DEBUG]    | Create Asset Folders: False                                                                        |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:225]  [DEBUG]    | Download URL Assets: False                                                                         |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:226]  [DEBUG]    | Sync Mode: append                                                                                  |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:227]  [DEBUG]    | Minimum Items: 1                                                                                   |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:228]  [DEBUG]    | Delete Below Minimum: True                                                                         |
[2022-05-26 01:10:34,302] [plex_meta_manager.py:229]  [DEBUG]    | Delete Not Scheduled: False                                                                        |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:230]  [DEBUG]    | Default Collection Order: None                                                                     |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:231]  [DEBUG]    | Missing Only Released: False                                                                       |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:232]  [DEBUG]    | Only Filter Missing: False                                                                         |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:233]  [DEBUG]    | Show Unmanaged: True                                                                               |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:234]  [DEBUG]    | Show Filtered: False                                                                               |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:235]  [DEBUG]    | Show Missing: True                                                                                 |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:236]  [DEBUG]    | Show Missing Assets: True                                                                          |
[2022-05-26 01:10:34,303] [plex_meta_manager.py:237]  [DEBUG]    | Save Missing: True                                                                                 |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:238]  [DEBUG]    | Clean Bundles: False                                                                               |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:239]  [DEBUG]    | Empty Trash: False                                                                                 |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:240]  [DEBUG]    | Optimize: False                                                                                    |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:241]  [DEBUG]    | Timeout: 60                                                                                        |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:251]  [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,304] [plex_meta_manager.py:252]  [INFO]     |====================================== Mapping Movies Library ======================================|
[2022-05-26 01:10:34,304] [plex_meta_manager.py:253]  [INFO]     |                                                                                                    |
[2022-05-26 01:10:34,304] [plex.py:476]               [INFO]     | Loading All Movies from Library: Movies                                                            |
[2022-05-26 01:13:28,000] [plex.py:485]               [INFO]     | Loaded 24111 Movies                                                                                |
[2022-05-26 01:13:28,001] [library.py:246]            [INFO]     | Mapping Movie Library: Movies                                                                      |
[2022-05-26 01:13:28,001] [library.py:247]            [INFO]     |                                                                                                    |
[2022-05-26 01:13:28,224] [convert.py:335]            [INFO]     | Mapping Error | local://612853                                 | No match in Plex for "Abraham"    |
[2022-05-26 01:13:28,257] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [157616]                                                                 |
[2022-05-26 01:13:28,258] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/605a2dfa51c175002ca84b0e          | No ID to convert for "AEW Double or Nothing 2020" |
[2022-05-26 01:13:28,264] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [141262]                                                                 |
[2022-05-26 01:13:28,264] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5f78c6d38d67e000418469a6          | No ID to convert for "AEW Full Gear 2020" |
[2022-05-26 01:13:28,269] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [136602]                                                                 |
[2022-05-26 01:13:28,269] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5f02cb2e554fdc0040dafc08          | No ID to convert for "AEW Revolution 2020" |
[2022-05-26 01:13:28,272] [convert.py:335]            [INFO]     | Mapping Error | local://781265                                 | No match in Plex for "After Porn Ends" |
[2022-05-26 01:13:28,272] [convert.py:335]            [INFO]     | Mapping Error | local://781264                                 | No match in Plex for "After Porn Ends 2" |
[2022-05-26 01:13:28,274] [convert.py:335]            [INFO]     | Mapping Error | local://781120                                 | No match in Plex for "Agatha Raisin and the Quiche of Death" |
[2022-05-26 01:13:28,628] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [128614]                                                                 |
[2022-05-26 01:13:28,628] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7db9353ad100045e87e43          | No ID to convert for "Alice in Dreamland" |
[2022-05-26 01:13:29,269] [convert.py:335]            [INFO]     | Mapping Error | local://779759                                 | No match in Plex for "Anne of Green Gables the Continuing Story" |
[2022-05-26 01:13:29,276] [convert.py:335]            [INFO]     | Mapping Error | local://809607                                 | No match in Plex for "Annie"      |
[2022-05-26 01:13:29,614] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [133616]                                                                 |
[2022-05-26 01:13:29,614] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5e833d13d78d060041e4d341          | No ID to convert for "The Assent" |
[2022-05-26 01:13:29,625] [convert.py:335]            [INFO]     | Mapping Error | local://779191                                 | No match in Plex for "Aurora Teagarden Mysteries Reunited and It Feels So Deadly" |
[2022-05-26 01:13:29,653] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [159108]                                                                 |
[2022-05-26 01:13:29,654] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/60798a910b35f60035191445          | No ID to convert for "B2: Stealth at War" |
[2022-05-26 01:13:30,050] [convert.py:335]            [INFO]     | Mapping Error | local://771274                                 | No match in Plex for "A Beautiful Place to Die a Marthas Vineyard Mystery" |
[2022-05-26 01:13:30,242] [convert.py:335]            [INFO]     | Mapping Error | local://613677                                 | No match in Plex for "Best Dog India" |
[2022-05-26 01:13:30,278] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [19338]                                                                  |
[2022-05-26 01:13:30,278] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/61b0f7ab04bef371fc37ede5          | No ID to convert for "Bigger Stronger Faster*" |
[2022-05-26 01:13:30,282] [convert.py:335]            [INFO]     | Mapping Error | local://778950                                 | No match in Plex for "Bill Burr One Night Stand" |
[2022-05-26 01:13:30,284] [convert.py:335]            [INFO]     | Mapping Error | local://783927                                 | No match in Plex for "Bill Hicks One Night Stand" |
[2022-05-26 01:13:30,868] [convert.py:335]            [INFO]     | Mapping Error | local://783764                                 | No match in Plex for "Blood Redd" |
[2022-05-26 01:13:30,882] [convert.py:335]            [INFO]     | Mapping Error | local://783670                                 | No match in Plex for "Bonnie and Clyde" |
[2022-05-26 01:13:30,917] [convert.py:335]            [INFO]     | Mapping Error | local://782979                                 | No match in Plex for "Bunny Lake Is Missing" |
[2022-05-26 01:13:31,491] [convert.py:335]            [INFO]     | Mapping Error | local://783497                                 | No match in Plex for "Calls"      |
[2022-05-26 01:13:31,496] [convert.py:335]            [INFO]     | Mapping Error | local://794762                                 | No match in Plex for "Caprica"    |
[2022-05-26 01:13:32,125] [convert.py:335]            [INFO]     | Mapping Error | local://782844                                 | No match in Plex for "A Cat in the Brain" |
[2022-05-26 01:13:32,127] [convert.py:335]            [INFO]     | Mapping Error | local://588600                                 | No match in Plex for "Category 7 the End of the World" |
[2022-05-26 01:13:32,329] [convert.py:335]            [INFO]     | Mapping Error | local://783557                                 | No match in Plex for "A Christmas Carol" |
[2022-05-26 01:13:32,339] [convert.py:335]            [INFO]     | Mapping Error | local://782372                                 | No match in Plex for "Chronicle Mysteries Recovered" |
[2022-05-26 01:13:32,339] [convert.py:335]            [INFO]     | Mapping Error | local://782369                                 | No match in Plex for "Chronicle Mysteries the Wrong Man" |
[2022-05-26 01:13:32,340] [convert.py:335]            [INFO]     | Mapping Error | local://782365                                 | No match in Plex for "Chronicle Mysteries Vines That Bind" |
[2022-05-26 01:13:32,342] [convert.py:335]            [INFO]     | Mapping Error | local://808333                                 | No match in Plex for "Cinderella III a Twist in Time" |
[2022-05-26 01:13:32,348] [convert.py:335]            [INFO]     | Mapping Error | local://781634                                 | No match in Plex for "Classic Albums Amy Winehouse Back to Black" |
[2022-05-26 01:13:32,352] [convert.py:335]            [INFO]     | Mapping Error | local://806061                                 | No match in Plex for "The Clockwork Girl" |
[2022-05-26 01:13:32,729] [convert.py:335]            [INFO]     | Mapping Error | local://647523                                 | No match in Plex for "Controlling Britney Spears" |
[2022-05-26 01:13:33,167] [convert.py:335]            [INFO]     | Mapping Error | local://781754                                 | No match in Plex for "Crossword Mysteries Riddle Me Dead" |
[2022-05-26 01:13:33,754] [convert.py:335]            [INFO]     | Mapping Error | local://781239                                 | No match in Plex for "Dead Drop"  |
[2022-05-26 01:13:33,779] [convert.py:335]            [INFO]     | Mapping Error | local://781046                                 | No match in Plex for "Death Riders" |
[2022-05-26 01:13:35,200] [convert.py:335]            [INFO]     | Mapping Error | local://780819                                 | No match in Plex for "Doctor Who the Day of the Doctor" |
[2022-05-26 01:13:35,201] [convert.py:335]            [INFO]     | Mapping Error | local://780815                                 | No match in Plex for "Doctor Who the Doctor the Widow and the Wardrobe" |
[2022-05-26 01:13:35,201] [convert.py:335]            [INFO]     | Mapping Error | local://780812                                 | No match in Plex for "Doctor Who the Time of the Doctor" |
[2022-05-26 01:13:35,459] [convert.py:335]            [INFO]     | Mapping Error | local://580584                                 | No match in Plex for "Echoes in the Darkness" |
[2022-05-26 01:13:35,805] [convert.py:335]            [INFO]     | Mapping Error | local://808270                                 | No match in Plex for "Elephant Kingdom" |
[2022-05-26 01:13:35,827] [convert.py:335]            [INFO]     | Mapping Error | local://806557                                 | No match in Plex for "The Even Stevens Movie" |
[2022-05-26 01:13:38,042] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [98929]                                                                  |
[2022-05-26 01:13:38,042] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7e710fb9b770040361435          | No ID to convert for "Gigantis the Fire Monster" |
[2022-05-26 01:13:38,994] [convert.py:335]            [INFO]     | Mapping Error | local://809697                                 | No match in Plex for "The Grinch Grinches the Cat in the Hat" |
[2022-05-26 01:13:39,006] [convert.py:335]            [INFO]     | Mapping Error | local://649995                                 | No match in Plex for "Hailey Dean Mysteries a Will to Kill" |
[2022-05-26 01:13:39,030] [convert.py:335]            [INFO]     | Mapping Error | local://807856                                 | No match in Plex for "Halloweentown High" |
[2022-05-26 01:13:39,031] [convert.py:335]            [INFO]     | Mapping Error | local://666390                                 | No match in Plex for "Halo Nightfall" |
[2022-05-26 01:13:39,355] [convert.py:335]            [INFO]     | Mapping Error | local://803546                                 | No match in Plex for "Home Run Showdown" |
[2022-05-26 01:13:39,829] [convert.py:335]            [INFO]     | Mapping Error | local://778886                                 | No match in Plex for "Ice"        |
[2022-05-26 01:13:39,832] [convert.py:335]            [INFO]     | Mapping Error | local://613454                                 | No match in Plex for "The Iceman Tapes Conversations With a Killer" |
[2022-05-26 01:13:39,848] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [332585]                                                                 |
[2022-05-26 01:13:39,848] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/61ebeab16de4bff2b091f10d          | No ID to convert for "Impact Wrestling Sacrifice 2022" |
[2022-05-26 01:13:40,265] [convert.py:335]            [INFO]     | Mapping Error | local://654985                                 | No match in Plex for "Inventing David Geffen" |
[2022-05-26 01:13:40,271] [convert.py:335]            [INFO]     | Mapping Error | local://809846                                 | No match in Plex for "Iron Sky"   |
[2022-05-26 01:13:40,490] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [138103]                                                                 |
[2022-05-26 01:13:40,491] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5f29094507a64c0040104f25          | No ID to convert for "The Jack in the Box" |
[2022-05-26 01:13:40,496] [convert.py:335]            [INFO]     | Mapping Error | local://716698                                 | No match in Plex for "The Jane Doe Murders" |
[2022-05-26 01:13:40,855] [convert.py:335]            [INFO]     | Mapping Error | local://612989                                 | No match in Plex for "Jesus"      |
[2022-05-26 01:13:41,055] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [99928]                                                                  |
[2022-05-26 01:13:41,055] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7e7361452720042d6b027          | No ID to convert for "Joe Lycett: I'm About to Lose Control And I Think Joe Lycett, Live" |
[2022-05-26 01:13:41,465] [convert.py:335]            [INFO]     | Mapping Error | local://809739                                 | No match in Plex for "Lassie the Voyager" |
[2022-05-26 01:13:42,579] [convert.py:335]            [INFO]     | Mapping Error | local://784113                                 | No match in Plex for "The Little Princess" |
[2022-05-26 01:13:43,916] [convert.py:335]            [INFO]     | Mapping Error | local://63008                                  | No match in Plex for "Marvel's Infinity Saga the Sacred Timeline" |
[2022-05-26 01:13:44,671] [convert.py:335]            [INFO]     | Mapping Error | local://618545                                 | No match in Plex for "Miles Davis Birth of the Cool" |
[2022-05-26 01:13:44,696] [convert.py:335]            [INFO]     | Mapping Error | local://707738                                 | No match in Plex for "Mitch Hedberg Uncut" |
[2022-05-26 01:13:45,099] [convert.py:335]            [INFO]     | Mapping Error | local://588991                                 | No match in Plex for "A Murder of Crows" |
[2022-05-26 01:13:45,365] [convert.py:335]            [INFO]     | Mapping Error | local://666829                                 | No match in Plex for "Mystery 101 Killer Timing" |
[2022-05-26 01:13:46,544] [convert.py:335]            [INFO]     | Mapping Error | local://665011                                 | No match in Plex for "No Direction Home Bob Dylan" |
[2022-05-26 01:13:46,553] [convert.py:335]            [INFO]     | Mapping Error | local://648367                                 | No match in Plex for "North Korea Life Inside the Secret State" |
[2022-05-26 01:13:47,623] [convert.py:335]            [INFO]     | Mapping Error | local://587836                                 | No match in Plex for "Parades.End.2012.Part5.720p.BluRay.H264.AAC-RARBG" |
[2022-05-26 01:13:48,774] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [31384]                                                                  |
[2022-05-26 01:13:48,775] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7ddeadcece1004133460a          | No ID to convert for "PSYCHO-PASS Sinners of the System: Case.3 - In the Realm Beyond Is ____" |
[2022-05-26 01:13:49,013] [convert.py:335]            [INFO]     | Mapping Error | local://806931                                 | No match in Plex for "The Rainbow Tribe" |
[2022-05-26 01:13:51,582] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [107478]                                                                 |
[2022-05-26 01:13:51,582] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7d95a51a04c003f19785a          | No ID to convert for "The Shonku Diaries: A Unicorn Adventure" |
[2022-05-26 01:13:51,821] [convert.py:335]            [INFO]     | Mapping Error | local://809811                                 | No match in Plex for "Sneakerella" |
[2022-05-26 01:13:52,092] [convert.py:335]            [INFO]     | Mapping Error | local://759997                                 | No match in Plex for "Solomon"    |
[2022-05-26 01:13:52,147] [convert.py:335]            [INFO]     | Mapping Error | local://809706                                 | No match in Plex for "Spunky's Circus Adventure" |
[2022-05-26 01:13:52,157] [convert.py:335]            [INFO]     | Mapping Error | local://612988                                 | No match in Plex for "St Paul"    |
[2022-05-26 01:13:52,736] [convert.py:335]            [INFO]     | Mapping Error | local://809847                                 | No match in Plex for "Sweet Land" |
[2022-05-26 01:13:53,333] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [127965]                                                                 |
[2022-05-26 01:13:53,333] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ea7db85020425003dfdd5b9          | No ID to convert for "Tight Loose" |
[2022-05-26 01:13:53,340] [convert.py:332]            [DEBUG]    | TMDb: [], IMDb: [], TVDb: [136036]                                                                 |
[2022-05-26 01:13:53,340] [convert.py:335]            [INFO]     | Mapping Error | plex://movie/5ed8a634c569d3004118c5e8          | No ID to convert for " Tijuana Bible" |
[2022-05-26 01:13:53,627] [convert.py:335]            [INFO]     | Mapping Error | local://575557                                 | No match in Plex for "To Catch a Killer" |
[2022-05-26 01:13:54,327] [convert.py:335]            [INFO]     | Mapping Error | local://778959                                 | No match in Plex for "Top Gear Middle East Special" |
[2022-05-26 01:13:55,833] [convert.py:335]            [INFO]     | Mapping Error | local://764682                                 | No match in Plex for "V C Andrews Hidden Jewel" |
[2022-05-26 01:13:56,151] [convert.py:335]            [INFO]     | Mapping Error | local://809678                                 | No match in Plex for "The Wayfarers" |
[2022-05-26 01:13:58,093] [convert.py:335]            [INFO]     | Mapping Error | local://620362                                 | No match in Plex for "XIII the Conspiracy" |
[2022-05-26 01:13:58,440] [library.py:261]            [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,440] [library.py:262]            [INFO]     | Processed 24111 Movies                                                                             |
[2022-05-26 01:13:58,441] [plex_meta_manager.py:261]  [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,441] [plex_meta_manager.py:262]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,441] [plex_meta_manager.py:262]  [INFO]     |                                    Running People Metadata File                                    |
[2022-05-26 01:13:58,442] [plex_meta_manager.py:262]  [INFO]     |                                      config/Movies/People.yml                                      |
[2022-05-26 01:13:58,442] [plex_meta_manager.py:262]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,442] [plex_meta_manager.py:275]  [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,443] [plex_meta_manager.py:276]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,443] [plex_meta_manager.py:276]  [INFO]     |                                            Collections                                             |
[2022-05-26 01:13:58,443] [plex_meta_manager.py:276]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,444] [plex_meta_manager.py:404]  [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,445] [plex_meta_manager.py:437]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,445] [plex_meta_manager.py:437]  [INFO]     |                                 Bong Joon-Ho Collection in Movies                                  |
[2022-05-26 01:13:58,446] [plex_meta_manager.py:437]  [INFO]     |====================================================================================================|
[2022-05-26 01:13:58,446] [plex_meta_manager.py:438]  [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,446] [plex_meta_manager.py:443]  [INFO]     |================================ Validating Bong Joon-Ho Attributes ================================|
[2022-05-26 01:13:58,447] [builder.py:241]            [DEBUG]    |                                                                                                    |
[2022-05-26 01:13:58,447] [builder.py:242]            [DEBUG]    | Validating Method: template                                                                        |
[2022-05-26 01:13:58,448] [meta.py:109]               [DEBUG]    | Value: ordereddict([('name', 'Director'), ('person', 21684)])                                      |
[2022-05-26 01:13:58,448] [builder.py:459]            [DEBUG]    |                                                                                                    |
[2022-05-26 01:13:58,449] [builder.py:460]            [DEBUG]    | Validating Method: tmdb_person                                                                     |
[2022-05-26 01:13:58,449] [builder.py:464]            [DEBUG]    | Value: 21684                                                                                       |
[2022-05-26 01:13:58,456] [builder.py:1588]           [INFO]     |                                                                                                    |
[2022-05-26 01:13:58,457] [builder.py:1589]           [INFO]     | Validating Method: smart_filter                                                                    |
[2022-05-26 01:13:58,457] [builder.py:1595]           [DEBUG]    | Value: {'all': {'director': 'tmdb', 'actor': 'tmdb'}, 'sort_by': 'year.asc'}                       |
[2022-05-26 01:14:51,355] [builder.py:588]            [DEBUG]    |                                                                                                    |
[2022-05-26 01:14:51,356] [builder.py:592]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-05-26 01:14:51,356] [builder.py:593]            [DEBUG]    | Value: +3_1_Bong Joon-Ho                                                                           |
[2022-05-26 01:14:51,394] [plex.py:721]               [DEBUG]    |                                                                                                    |
[2022-05-26 01:14:51,395] [plex.py:724]               [DEBUG]    | Looking for: Bong Joon-Ho                                                                          |
[2022-05-26 01:14:51,395] [builder.py:749]            [INFO]     |                                                                                                    |
[2022-05-26 01:14:51,395] [builder.py:750]            [INFO]     | Validation Successful                                                                              |
[2022-05-26 01:14:51,396] [plex_meta_manager.py:447]  [INFO]     |                                                                                                    |
[2022-05-26 01:14:51,396] [plex_meta_manager.py:449]  [INFO]     |================================= Running Bong Joon-Ho Collection ==================================|
[2022-05-26 01:14:51,396] [plex_meta_manager.py:455]  [INFO]     |                                                                                                    |
[2022-05-26 01:14:51,397] [plex_meta_manager.py:456]  [INFO]     | Smart Movie Filter                                                                                 |
                                                                 | Sort By: year.asc
                                                                 | Filter:
                                                                 |   Match all of the following:
                                                                 |     Director is Bong Joon-ho
                                                                 |     Actor is Bong Joon-ho
[2022-05-26 01:14:51,398] [plex.py:812]               [DEBUG]    | /library/sections/1/all?type=1&sort=year&director=131127&and=1&actor=190272
[2022-05-26 01:14:51,438] [plex_meta_manager.py:501]  [INFO]     | 
[2022-05-26 01:14:51,438] [plex_meta_manager.py:502]  [INFO]     | Collection Minimum: 1 not met for Bong Joon-Ho Collection
[2022-05-26 01:14:51,439] [plex_meta_manager.py:576]  [INFO]     | 
[2022-05-26 01:14:51,439] [plex_meta_manager.py:577]  [INFO]     |====================================================================================================|
[2022-05-26 01:14:51,439] [plex_meta_manager.py:577]  [INFO]     |                                  Finished Bong Joon-Ho Collection                                  |
[2022-05-26 01:14:51,440] [plex_meta_manager.py:577]  [INFO]     |                                    Collection Run Time: 0:00:52                                    |
[2022-05-26 01:14:51,440] [plex_meta_manager.py:577]  [INFO]     |====================================================================================================|
[2022-05-26 01:14:51,440] [plex_meta_manager.py:437]  [INFO]     |====================================================================================================|
[2022-05-26 01:14:51,441] [plex_meta_manager.py:437]  [INFO]     |                               Christopher Nolan Collection in Movies                               |
[2022-05-26 01:14:51,441] [plex_meta_manager.py:437]  [INFO]     |====================================================================================================|
[2022-05-26 01:14:51,442] [plex_meta_manager.py:438]  [INFO]     |                                                                                                    |
[2022-05-26 01:14:51,442] [plex_meta_manager.py:443]  [INFO]     |============================= Validating Christopher Nolan Attributes ==============================|
[2022-05-26 01:14:51,443] [builder.py:241]            [DEBUG]    |                                                                                                    |
[2022-05-26 01:14:51,443] [builder.py:242]            [DEBUG]    | Validating Method: template                                                                        |
[2022-05-26 01:14:51,444] [meta.py:109]               [DEBUG]    | Value: ordereddict([('name', 'Director'), ('person', 525)])                                        |
[2022-05-26 01:14:51,444] [builder.py:459]            [DEBUG]    |                                                                                                    |
[2022-05-26 01:14:51,445] [builder.py:460]            [DEBUG]    | Validating Method: tmdb_person                                                                     |
[2022-05-26 01:14:51,445] [builder.py:464]            [DEBUG]    | Value: 525                                                                                         |
[2022-05-26 01:14:51,453] [builder.py:1588]           [INFO]     |                                                                                                    |
[2022-05-26 01:14:51,453] [builder.py:1589]           [INFO]     | Validating Method: smart_filter                                                                    |
[2022-05-26 01:14:51,453] [builder.py:1595]           [DEBUG]    | Value: {'all': {'director': 'tmdb', 'actor': 'tmdb'}, 'sort_by': 'year.asc'}                       |
