[2022-05-26 01:45:00,470] [plex_meta_manager.py:122]  [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,474] [plex_meta_manager.py:123]  [INFO]     |                                                                                                    |
[2022-05-26 01:45:00,474] [plex_meta_manager.py:124]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-05-26 01:45:00,474] [plex_meta_manager.py:125]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-05-26 01:45:00,474] [plex_meta_manager.py:126]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-05-26 01:45:00,475] [plex_meta_manager.py:127]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-05-26 01:45:00,475] [plex_meta_manager.py:128]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-05-26 01:45:00,475] [plex_meta_manager.py:129]  [INFO]     |                                                                            |___/                   |
[2022-05-26 01:45:00,475] [plex_meta_manager.py:130]  [INFO]     |     Version: 1.16.5                                                                                |
[2022-05-26 01:45:00,512] [plex_meta_manager.py:149]  [DEBUG]    |====================================================================================================|
[2022-05-26 01:45:00,512] [plex_meta_manager.py:150]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-05-26 01:45:00,512] [plex_meta_manager.py:151]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-05-26 01:45:00,513] [plex_meta_manager.py:152]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-05-26 01:45:00,513] [plex_meta_manager.py:153]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-05-26 01:45:00,513] [plex_meta_manager.py:154]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-05-26 01:45:00,513] [plex_meta_manager.py:155]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-05-26 01:45:00,514] [plex_meta_manager.py:156]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-05-26 01:45:00,514] [plex_meta_manager.py:157]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-05-26 01:45:00,514] [plex_meta_manager.py:158]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-05-26 01:45:00,515] [plex_meta_manager.py:159]  [DEBUG]    | --run-metadata-files (PMM_METADATA_FILES): None                                                    |
[2022-05-26 01:45:00,515] [plex_meta_manager.py:160]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-05-26 01:45:00,515] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-ghost (PMM_IGNORE_GHOST): False                                                           |
[2022-05-26 01:45:00,516] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-05-26 01:45:00,516] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-05-26 01:45:00,516] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-05-26 01:45:00,518] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-05-26 01:45:00,518] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-05-26 01:45:00,518] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-05-26 01:45:00,518] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-05-26 01:45:00,519] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-05-26 01:45:00,519] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-05-26 01:45:00,519] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-05-26 01:45:00,520] [plex_meta_manager.py:172]  [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,520] [plex_meta_manager.py:172]  [INFO]     |                                            Starting Run                                            |
[2022-05-26 01:45:00,520] [plex_meta_manager.py:172]  [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,521] [config.py:58]              [INFO]     | Locating config...                                                                                 |
[2022-05-26 01:45:00,521] [config.py:64]              [INFO]     | Using //config/config.yml as config                                                                |
[2022-05-26 01:45:00,574] [config.py:252]             [WARNING]  | Config Warning: Path does not exist: /config/assets                                                |
[2022-05-26 01:45:00,574] [config.py:282]             [WARNING]  | Config Warning: No Paths exist using ['//config/assets'] as default                                |
[2022-05-26 01:45:00,575] [config.py:338]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,575] [config.py:354]             [WARNING]  | notifiarr attribute not found                                                                      |
[2022-05-26 01:45:00,576] [config.py:373]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,576] [config.py:378]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-05-26 01:45:00,711] [config.py:386]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-05-26 01:45:00,712] [config.py:390]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,712] [config.py:404]             [WARNING]  | omdb attribute not found                                                                           |
[2022-05-26 01:45:00,713] [config.py:406]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,713] [config.py:421]             [WARNING]  | mdblist attribute not found                                                                        |
[2022-05-26 01:45:00,713] [config.py:423]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,714] [config.py:427]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-05-26 01:45:00,839] [config.py:438]             [INFO]     | Trakt Connection Successful                                                                        |
[2022-05-26 01:45:00,840] [config.py:442]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,840] [config.py:458]             [WARNING]  | mal attribute not found                                                                            |
[2022-05-26 01:45:00,840] [config.py:473]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:00,841] [config.py:496]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-05-26 01:45:01,172] [config.py:508]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,173] [config.py:510]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-05-26 01:45:01,173] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,173] [config.py:581]             [INFO]     |                                        Movies Configuration                                        |
[2022-05-26 01:45:01,174] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,174] [config.py:582]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,174] [config.py:583]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-05-26 01:45:01,175] [config.py:584]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,176] [config.py:750]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,176] [config.py:751]             [INFO]     |======================================== Plex Configuration ========================================|
[2022-05-26 01:45:01,177] [library.py:107]            [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,177] [library.py:109]            [INFO]     | Using Asset Directory: //config/assets                                                             |
[2022-05-26 01:45:01,324] [config.py:761]             [INFO]     | Movies Library Connection Successful                                                               |
[2022-05-26 01:45:01,324] [config.py:769]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,325] [config.py:770]             [INFO]     |===================================== Scanning Metadata Files ======================================|
[2022-05-26 01:45:01,325] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,325] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/People.yml                                                    |
[2022-05-26 01:45:01,326] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,345] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully                                                                  |
[2022-05-26 01:45:01,346] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,346] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Franchises.yml                                                |
[2022-05-26 01:45:01,346] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,452] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully                                                                  |
[2022-05-26 01:45:01,452] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,453] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Studios.yml                                                   |
[2022-05-26 01:45:01,453] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,471] [meta.py:100]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 95, in load_file
                                                                 |     data, _, _ = yaml.util.load_yaml_guess_indent(content)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/util.py", line 186, in load_yaml_guess_indent
                                                                 |     return yaml.load(yaml_str, **kw), indent, block_seq_indent  # type: ignore
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
                                                                 |     return constructor.get_single_data()
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
                                                                 |     return self.construct_document(node)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 131, in construct_document
                                                                 |     for _dummy in generator:
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1569, in construct_yaml_map
                                                                 |     self.construct_mapping(node, data, deep=True)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1452, in construct_mapping
                                                                 |     value = self.construct_object(value_node, deep=deep)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
                                                                 |     data = self.construct_non_recursive_object(node)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 196, in construct_non_recursive_object
                                                                 |     for _dummy in generator:
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1569, in construct_yaml_map
                                                                 |     self.construct_mapping(node, data, deep=True)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 1453, in construct_mapping
                                                                 |     if self.check_mapping_key(node, key_node, maptyp, key, value):
                                                                 |   File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 294, in check_mapping_key
                                                                 |     raise DuplicateKeyError(*args)
                                                                 | ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
                                                                 |   in "<unicode string>", line 12, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 12)
                                                                 | found duplicate key "Disney Animated" with value "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/71183')])), ('sort_title', '+++++++DisneyLiveAction'), ('imdb_list', ['https://www.imdb.com/list/ls083312980/'])])" (original value: "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/11845')])), ('sort_title', '+++++++DisneyAnimated'), ('trakt_list', ['https://trakt.tv/users/kieranr27/lists/studio-disney-animation-copy?sort=released,desc'])])")
                                                                 |   in "<unicode string>", line 17, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 17)
                                                                 | 
                                                                 | To suppress this check see:
                                                                 |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
                                                                 | 
                                                                 | 
[2022-05-26 01:45:01,481] [library.py:125]            [ERROR]    | YAML Error: while constructing a mapping
                                                                 |   in "<unicode string>", line 12, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 12)
                                                                 | found duplicate key "Disney Animated" with value "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/71183')])), ('sort_title', '+++++++DisneyLiveAction'), ('imdb_list', ['https://www.imdb.com/list/ls083312980/'])])" (original value: "ordereddict([('template', ordereddict([('name', 'Studio'), ('poster', 'https://theposterdb.com/api/assets/11845')])), ('sort_title', '+++++++DisneyAnimated'), ('trakt_list', ['https://trakt.tv/users/kieranr27/lists/studio-disney-animation-copy?sort=released,desc'])])")
                                                                 |   in "<unicode string>", line 17, column 3:
                                                                 |       Disney Animated:
                                                                 |       ^ (line: 17)
                                                                 | 
                                                                 | To suppress this check see:
                                                                 |     http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
                                                                 | 
[2022-05-26 01:45:01,484] [meta.py:267]               [INFO]     | 
[2022-05-26 01:45:01,484] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Holiday.yml
[2022-05-26 01:45:01,484] [meta.py:269]               [INFO]     | 
[2022-05-26 01:45:01,535] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully
[2022-05-26 01:45:01,536] [meta.py:267]               [INFO]     | 
[2022-05-26 01:45:01,536] [meta.py:268]               [INFO]     | Loading Metadata File: config/Movies/Charts.yml
[2022-05-26 01:45:01,537] [meta.py:269]               [INFO]     | 
[2022-05-26 01:45:01,556] [meta.py:599]               [INFO]     | Metadata File Loaded Successfully
[2022-05-26 01:45:01,557] [config.py:853]             [INFO]     | 
[2022-05-26 01:45:01,557] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,558] [config.py:581]             [INFO]     |                                       TV Shows Configuration                                       |
[2022-05-26 01:45:01,558] [config.py:581]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,558] [config.py:582]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,558] [config.py:583]             [INFO]     | Connecting to TV Shows Library...                                                                  |
[2022-05-26 01:45:01,558] [config.py:584]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,559] [config.py:750]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,559] [config.py:751]             [INFO]     |======================================== Plex Configuration ========================================|
[2022-05-26 01:45:01,560] [library.py:107]            [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,560] [library.py:109]            [INFO]     | Using Asset Directory: //config/assets                                                             |
[2022-05-26 01:45:01,686] [config.py:761]             [INFO]     | TV Shows Library Connection Successful                                                             |
[2022-05-26 01:45:01,687] [config.py:769]             [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,687] [config.py:770]             [INFO]     |===================================== Scanning Metadata Files ======================================|
[2022-05-26 01:45:01,687] [meta.py:267]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,688] [meta.py:268]               [INFO]     | Loading Metadata File: config/TVShows.yml                                                          |
[2022-05-26 01:45:01,688] [meta.py:269]               [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,689] [meta.py:100]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/meta.py", line 94, in load_file
                                                                 |     raise Failed(f"File Error: File does not exist {os.path.abspath(file_path)}")
                                                                 | modules.util.Failed: File Error: File does not exist /config/TVShows.yml
                                                                 | 
[2022-05-26 01:45:01,690] [library.py:125]            [ERROR]    | YAML Error: File Error: File does not exist /config/TVShows.yml
[2022-05-26 01:45:01,690] [config.py:853]             [INFO]     | 
[2022-05-26 01:45:01,691] [config.py:856]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,691] [config.py:861]             [INFO]     | 2 Plex Library Connections Successful                                                              |
[2022-05-26 01:45:01,691] [config.py:865]             [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,692] [plex_meta_manager.py:211]  [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,692] [plex_meta_manager.py:212]  [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,693] [plex_meta_manager.py:212]  [INFO]     |                                           Movies Library                                           |
[2022-05-26 01:45:01,693] [plex_meta_manager.py:212]  [INFO]     |====================================================================================================|
[2022-05-26 01:45:01,693] [plex_meta_manager.py:217]  [DEBUG]    |                                                                                                    |
[2022-05-26 01:45:01,694] [plex_meta_manager.py:218]  [DEBUG]    | Mapping Name: Movies                                                                               |
[2022-05-26 01:45:01,694] [plex_meta_manager.py:219]  [DEBUG]    | Folder Name: Movies                                                                                |
[2022-05-26 01:45:01,694] [plex_meta_manager.py:220]  [DEBUG]    | Missing Path: //config/Movies_missing.yml                                                          |
[2022-05-26 01:45:01,695] [plex_meta_manager.py:222]  [DEBUG]    | Asset Directory: //config/assets                                                                   |
[2022-05-26 01:45:01,695] [plex_meta_manager.py:223]  [DEBUG]    | Asset Folders: True                                                                                |
[2022-05-26 01:45:01,696] [plex_meta_manager.py:224]  [DEBUG]    | Create Asset Folders: False                                                                        |
[2022-05-26 01:45:01,696] [plex_meta_manager.py:225]  [DEBUG]    | Download URL Assets: False                                                                         |
[2022-05-26 01:45:01,697] [plex_meta_manager.py:226]  [DEBUG]    | Sync Mode: append                                                                                  |
[2022-05-26 01:45:01,697] [plex_meta_manager.py:227]  [DEBUG]    | Minimum Items: 1                                                                                   |
[2022-05-26 01:45:01,697] [plex_meta_manager.py:228]  [DEBUG]    | Delete Below Minimum: True                                                                         |
[2022-05-26 01:45:01,698] [plex_meta_manager.py:229]  [DEBUG]    | Delete Not Scheduled: False                                                                        |
[2022-05-26 01:45:01,698] [plex_meta_manager.py:230]  [DEBUG]    | Default Collection Order: None                                                                     |
[2022-05-26 01:45:01,706] [plex_meta_manager.py:231]  [DEBUG]    | Missing Only Released: False                                                                       |
[2022-05-26 01:45:01,706] [plex_meta_manager.py:232]  [DEBUG]    | Only Filter Missing: False                                                                         |
[2022-05-26 01:45:01,707] [plex_meta_manager.py:233]  [DEBUG]    | Show Unmanaged: True                                                                               |
[2022-05-26 01:45:01,707] [plex_meta_manager.py:234]  [DEBUG]    | Show Filtered: False                                                                               |
[2022-05-26 01:45:01,708] [plex_meta_manager.py:235]  [DEBUG]    | Show Missing: True                                                                                 |
[2022-05-26 01:45:01,708] [plex_meta_manager.py:236]  [DEBUG]    | Show Missing Assets: True                                                                          |
[2022-05-26 01:45:01,708] [plex_meta_manager.py:237]  [DEBUG]    | Save Missing: True                                                                                 |
[2022-05-26 01:45:01,709] [plex_meta_manager.py:238]  [DEBUG]    | Clean Bundles: False                                                                               |
[2022-05-26 01:45:01,709] [plex_meta_manager.py:239]  [DEBUG]    | Empty Trash: False                                                                                 |
[2022-05-26 01:45:01,709] [plex_meta_manager.py:240]  [DEBUG]    | Optimize: False                                                                                    |
[2022-05-26 01:45:01,710] [plex_meta_manager.py:241]  [DEBUG]    | Timeout: 60                                                                                        |
[2022-05-26 01:45:01,710] [plex_meta_manager.py:251]  [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,711] [plex_meta_manager.py:252]  [INFO]     |====================================== Mapping Movies Library ======================================|
[2022-05-26 01:45:01,711] [plex_meta_manager.py:253]  [INFO]     |                                                                                                    |
[2022-05-26 01:45:01,711] [plex.py:476]               [INFO]     | Loading All Movies from Library: Movies                                                            |
